In [1]:
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='vYdLFvS7OIFtrvWEDBnshv8-8wT-1U2HCqOLpQTFwYFK',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.jp-tok.cloud-object-storage.appdomain.cloud')

#daily report
bucket = 'forex-donotdelete-pr-z4qvpns5xgagyh'
object_key = 'daily_report.csv'
body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
df_1 = pd.read_csv(body)

#trades
object_key = 'trades.csv'
body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
df_2 = pd.read_csv(body)

#login
object_key = 'login.csv'
body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
df_3 = pd.read_csv(body)

#print
#df_1.head(10)
df_2.head(10)
#df_3.head(10)

,ticket,login,symbol,cmd,volume,open_time,open_price,close_time,close_price,tp,sl,reason,commission,swaps,profit,volume_usd
0,68880703,7062462,XAUUSD,0,0.01,1707843941,1991.35000,1708013114,2003.01000,0.00000,0.00000,1,0.00,-1.12,10.83,3994.36
1,68880910,7062462,XAUUSD,0,0.02,1707844129,1990.30000,1708013110,2002.76000,0.00000,0.00000,1,0.00,-2.25,23.16,7986.12
2,68120690,813125,US2000,0,1.00,1706083005,1983.22000,1706114503,1996.68000,2012.34000,1980.03000,1,0.00,0.00,105.42,39799.00
3,68169249,813125,US2000,0,2.00,1706139371,1960.62000,1706200143,1991.51000,2331.85000,1958.94000,1,0.00,-7.21,485.26,79042.60
4,68186877,88945036,NZDUSD,0,0.13,1706169600,0.61062,1706197106,0.61317,0.61312,0.55059,1,-0.91,0.00,33.15,15909.27
5,67824283,7063824,XRPUSD,1,0.01,1705356060,0.57940,1705364236,0.57441,0.57444,0.58424,1,0.00,0.00,0.00,1.15
6,68879706,7062462,XAUUSD,0,0.02,1707843610,1995.38000,1708008593,1998.78000,0.00000,0.00000,1,0.00,-2.25,6.33,7988.32
7,68089772,811046,GBPUSD,0,0.01,1706029201,1.26820,1706091454,1.27114,0.00000,1.27116,1,0.00,-0.02,2.94,2539.34
8,67824307,7063824,XRPUSD,1,0.01,1705356181,0.57964,1705364235,0.57452,0.57454,0.58434,1,0.00,0.00,0.01,1.15
9,67824315,7063824,XRPUSD,0,0.01,1705356305,0.58142,1705359072,0.57671,0.58652,0.57672,1,0.00,0.00,0.00,1.16

In [2]:
df_2['open_time'] = pd.to_datetime(df_2['open_time'], unit='s')
df_2['open_time'] = df_2['open_time'].dt.tz_localize('UTC')
df_2['open_time'] = df_2['open_time'].dt.tz_localize(None)
df_2['close_time'] = pd.to_datetime(df_2['close_time'], unit='s')
df_2['close_time'] = df_2['close_time'].dt.tz_localize('UTC')
df_2['close_time'] = df_2['close_time'].dt.tz_localize(None)
df_2.head(10)

,ticket,login,symbol,cmd,volume,open_time,open_price,close_time,close_price,tp,sl,reason,commission,swaps,profit,volume_usd
0,68880703,7062462,XAUUSD,0,0.01,2024-02-13 17:05:41,1991.35000,2024-02-15 16:05:14,2003.01000,0.00000,0.00000,1,0.00,-1.12,10.83,3994.36
1,68880910,7062462,XAUUSD,0,0.02,2024-02-13 17:08:49,1990.30000,2024-02-15 16:05:10,2002.76000,0.00000,0.00000,1,0.00,-2.25,23.16,7986.12
2,68120690,813125,US2000,0,1.00,2024-01-24 07:56:45,1983.22000,2024-01-24 16:41:43,1996.68000,2012.34000,1980.03000,1,0.00,0.00,105.42,39799.00
3,68169249,813125,US2000,0,2.00,2024-01-24 23:36:11,1960.62000,2024-01-25 16:29:03,1991.51000,2331.85000,1958.94000,1,0.00,-7.21,485.26,79042.60
4,68186877,88945036,NZDUSD,0,0.13,2024-01-25 08:00:00,0.61062,2024-01-25 15:38:26,0.61317,0.61312,0.55059,1,-0.91,0.00,33.15,15909.27
5,67824283,7063824,XRPUSD,1,0.01,2024-01-15 22:01:00,0.57940,2024-01-16 00:17:16,0.57441,0.57444,0.58424,1,0.00,0.00,0.00,1.15
6,68879706,7062462,XAUUSD,0,0.02,2024-02-13 17:00:10,1995.38000,2024-02-15 14:49:53,1998.78000,0.00000,0.00000,1,0.00,-2.25,6.33,7988.32
7,68089772,811046,GBPUSD,0,0.01,2024-01-23 17:00:01,1.26820,2024-01-24 10:17:34,1.27114,0.00000,1.27116,1,0.00,-0.02,2.94,2539.34
8,67824307,7063824,XRPUSD,1,0.01,2024-01-15 22:03:01,0.57964,2024-01-16 00:17:15,0.57452,0.57454,0.58434,1,0.00,0.00,0.01,1.15
9,67824315,7063824,XRPUSD,0,0.01,2024-01-15 22:05:05,0.58142,2024-01-15 22:51:12,0.57671,0.58652,0.57672,1,0.00,0.00,0.00,1.16

In [3]:
df_2 = pd.merge(df_2, df_3[['login', 'account_currency']], on='login', how='left')
df_2.head(10)

,ticket,login,symbol,cmd,volume,open_time,open_price,close_time,close_price,tp,sl,reason,commission,swaps,profit,volume_usd,account_currency
0,68880703,7062462,XAUUSD,0,0.01,2024-02-13 17:05:41,1991.35000,2024-02-15 16:05:14,2003.01000,0.00000,0.00000,1,0.00,-1.12,10.83,3994.36,EUR
1,68880910,7062462,XAUUSD,0,0.02,2024-02-13 17:08:49,1990.30000,2024-02-15 16:05:10,2002.76000,0.00000,0.00000,1,0.00,-2.25,23.16,7986.12,EUR
2,68120690,813125,US2000,0,1.00,2024-01-24 07:56:45,1983.22000,2024-01-24 16:41:43,1996.68000,2012.34000,1980.03000,1,0.00,0.00,105.42,39799.00,GBP
3,68169249,813125,US2000,0,2.00,2024-01-24 23:36:11,1960.62000,2024-01-25 16:29:03,1991.51000,2331.85000,1958.94000,1,0.00,-7.21,485.26,79042.60,GBP
4,68186877,88945036,NZDUSD,0,0.13,2024-01-25 08:00:00,0.61062,2024-01-25 15:38:26,0.61317,0.61312,0.55059,1,-0.91,0.00,33.15,15909.27,USD
5,67824283,7063824,XRPUSD,1,0.01,2024-01-15 22:01:00,0.57940,2024-01-16 00:17:16,0.57441,0.57444,0.58424,1,0.00,0.00,0.00,1.15,USD
6,68879706,7062462,XAUUSD,0,0.02,2024-02-13 17:00:10,1995.38000,2024-02-15 14:49:53,1998.78000,0.00000,0.00000,1,0.00,-2.25,6.33,7988.32,EUR
7,68089772,811046,GBPUSD,0,0.01,2024-01-23 17:00:01,1.26820,2024-01-24 10:17:34,1.27114,0.00000,1.27116,1,0.00,-0.02,2.94,2539.34,USD
8,67824307,7063824,XRPUSD,1,0.01,2024-01-15 22:03:01,0.57964,2024-01-16 00:17:15,0.57452,0.57454,0.58434,1,0.00,0.00,0.01,1.15,USD
9,67824315,7063824,XRPUSD,0,0.01,2024-01-15 22:05:05,0.58142,2024-01-15 22:51:12,0.57671,0.58652,0.57672,1,0.00,0.00,0.00,1.16,USD